server {
    listen 80;
    server_name staging.dockerfx.trade;

    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s ipv6=off;
    set $backend_staging "forex-backend-staging:3002";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass         http://$backend_staging;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_read_timeout 60s;
    }

    location /ws {
        proxy_pass         http://$backend_staging;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }

    location /webhook {
        proxy_pass http://$backend_staging;
    }

    location /health {
        proxy_pass http://$backend_staging/health;
    }

    server_tokens off;
}
