apiVersion: 1

policies:
  - orgId: 1
    receiver: Telegram Trading
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: Telegram Trading
        matchers:
          - severity =~ "critical|warning"
        continue: false
